apiVersion: apps/v1
kind: Deployment
metadata:
  name: erbdetector
  labels:
    app: erbdetector
spec:
  selector:
    matchLabels:
      app: erbdetector
  template:
    metadata:
      labels:
        app: erbdetector
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: false
        image: erbdetector
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: erbdetector
spec:
  type: NodePort
  selector:
    app: erbdetector
  ports:
    - name: prometheus
      port: 5005
      targetPort: 5005
    - name: http
      port: 5000
      targetPort: 5000
