{
 "title": "Drift Detection",
 "panels": [
  { "title": "Drift Detection Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Adwin Alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "adwin_alerts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Drift Score:  Hellinger Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "drift_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests Total ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Adwin Alerts Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "adwin_alerts_created", "legendFormat": "__auto" }
   ]
  }
 ]
}