# kubernetes-manifests/otelcollector.yaml
# source(s):
#       https://prometheus.io/docs/guides/opentelemetry/
#       https://opentelemetry.io/docs/languages/sdk-configuration/general/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcollector
  labels:
    app: otelcollector
spec:
  selector:
    matchLabels:
      app: otelcollector
  template:
    metadata:
      labels:
        app: otelcollector
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: false
        image: otelcollector
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "http/protobuf"
          - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
            value: "http://prometheus:9090/api/v1/otlp/v1/metrics"
          - name: OTEL_TRACES_EXPORTER
            value: "none"
          - name: OTEL_LOGS_EXPORTER
            value: "none"
          - name: OTEL_METRIC_EXPORT_INTERVAL
            value: "15000"
---
apiVersion: v1
kind: Service
metadata:
  name: otelcollector
  labels:
    app: otelcollector
spec:
  type: ClusterIP
  selector:
    app: otelcollector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
#     - name: metrics
#       port: 8889
#       targetPort: 8889
