apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcollector
  labels:
    app: otelcollector
spec:
  selector:
    matchLabels:
      app: otelcollector
  template:
    metadata:
      labels:
        app: otelcollector
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: false
        image: otelcollector
        ports:
          - name: prometheus
            containerPort: 8888  # Ensure this matches the exporter config
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: otelcollector
  labels:
    app: otelcollector
spec:
  type: ClusterIP
  selector:
    app: otelcollector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: prometheus
      port: 8888  # Update to match the container's Prometheus exporter port
      targetPort: 8888
