# src/prometheus/prometheus.yml

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]

  # Scrape OpenTelemetry Collector's Prometheus Exporter endpoint
  - job_name: "otelcol"
    static_configs:
      - targets: ["otelcollector:8888"]
    scrape_interval: 30s
    scrape_timeout: 10s  # Extend timeout

