# src/prometheus/prometheus.yml

remote_write:
- url: http://localhost:9090/v1/api/write

scrape_configs:
  # Scrape the Flask app
  - job_name: "erbdetector"
    static_configs:
      - targets: ["erbdetector:5000"]

  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
