# TARGET: src/prometheus/prometheus.yml


global:
  scrape_interval: 15s

scrape_configs:
  # Scrape the Flask app
  - job_name: "erbdetector"
    static_configs:
      - targets: ["erbdetector:5000"]

  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]

  - job_name: 'recommendation_service'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['recommendationservice:9464']


