# src/otelcollector/otel-collector-config.yaml
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write
# https://prometheus.io/docs/guides/opentelemetry/
# https://prometheus.io/docs/specs/remote_write_spec_2_0/
# https://prometheus.io/docs/prometheus/2.55/storage/#overview
# https://prometheus.io/docs/prometheus/2.55/configuration/configuration/#remote_read
# https://opentelemetry.io/docs/collector/configuration/#exporters
# https://last9.io/blog/prometheusremotewriteexporter-a-comprehensive-guide/

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    send_batch_size: 100
    timeout: 10s

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
    timeout: 10s
    resource_to_telemetry_conversion:
      enabled: true


service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: []

  telemetry:
    metrics:
      level: "detailed"

