receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  # Data sources: metrics
  prometheus:
    endpoint: 0.0.0.0:8888
    namespace: default

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]  # Ensure Prometheus Exporter is included
