# src/otelcollector/otel-collector-config.yaml

receivers:
  otlp: # the OTLP receiver the app is sending metrics to
    protocols:
      grpc:
    endpoint: 0.0.0.0:4317

exporters:
  prometheusremotewrite: # the PRW exporter, to ingest metrics to backend
    endpoint: http://prometheus:9090/v1/api/write
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheusremotewrite,debug]